{{- if .Values.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: qdrant
spec:
  serviceName: qdrant
  replicas: 1
  selector:
    matchLabels:
      app: qdrant
  template:
    metadata:
      labels:
        app: qdrant
    spec:
      serviceAccountName: qdrant-sa

      # THIS is the fix
      securityContext:
        fsGroup: 1000

      containers:
        - name: qdrant
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: http
              containerPort: 6333
            - name: grpc
              containerPort: 6334

          env:
            - name: QDRANT__SERVICE__HOST
              value: "0.0.0.0"
            - name: QDRANT__SERVICE__HTTP_PORT
              value: "6333"
            - name: QDRANT__SERVICE__GRPC_PORT
              value: "6334"
            - name: QDRANT__STORAGE__STORAGE_PATH
              value: "/qdrant/storage"

          volumeMounts:
            - name: qdrant-data
              mountPath: /qdrant/storage

          resources:
            {{ toYaml .Values.resources | nindent 12 }}

      volumes:
        - name: qdrant-data
          emptyDir: {}
{{- end }}
