apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: {{ .Values.namespace }}
  labels:
    app: jaeger
spec:
  type: {{ .Values.jaeger.service.type }}
  selector:
    app: jaeger
  ports:
    - name: query
      port: {{ .Values.jaeger.service.queryPort }}
      targetPort: 16686
    - name: collector-grpc
      port: {{ .Values.jaeger.service.collectorGrpcPort }}
      targetPort: 14250
    - name: collector-http
      port: {{ .Values.jaeger.service.collectorHttpPort }}
      targetPort: 14268
